// Types
export default {
  GET_CONTRIBUTES: "contributes/GET_CONTRIBUTES",
  GET_CONTRIBUTES_SUCCESS: "contributes/GET_CONTRIBUTES_SUCCESS",
  GET_CONTRIBUTES_FAILED: "contributes/GET_CONTRIBUTES_FAILED",
};
