# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Git global config
        run: |
          git config --global user.email intecs@itfac.mrt.ac.lk
          git config --global user.name INTECS-ITFAC
          git remote set-url origin https://${{secrets.PAT}}@github.com/INTECS-ITFAC/intecs_webapp_front-end.git
      - name: Deploy to GH-Pages
        run: npm run deploy
        with:
          github_token: ${{secrets.PAT}}
      - name: Updating Domain
        run: echo "Update domain"
